name: 'Doge'
description: 'Update files to doge cdn.'
inputs:
  ak:  # id of input
    description: 'AK'
    required: true
    default: '111'
  sk:  # id of input
    description: 'SK'
    required: true
    default: '222'  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: './dist/index.js'