on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Doge
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          ak: '888'
          sk: '999'
      # Use the output from the `hello` step
      - name: Time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
